add: component for US01 .jsx .css and data.json for theme
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-Postify pull request #22
Opened 2023-11-08 15:57 UTC by Lambseb

2023-11-08 15:58 UTC, Chikoulat approved these changes

2023-11-08 17:33 UTC, ioayoub requested changes
Be careful with css files naming, they must be in lowercase.

2023-11-08 17:33 UTC, ioayoub commented on frontend/src/components/ButtonsByTheme.jsx
> +  useEffect(() => {
useEffect is useless here, you can initialize your themeButton with data

2023-11-09 08:50 UTC, ioayoub requested changes

2023-11-09 08:50 UTC, ioayoub commented on frontend/src/components/ButtonsByTheme.jsx
> +  setQuery: PropTypes.string.isRequired,
setQuery is a function not a string

2023-11-09 09:01 UTC, ioayoub requested changes

2023-11-09 10:23 UTC, Lambseb commented
all are fixed.

2023-11-09 11:11 UTC, ioayoub approved these changes

2023-11-09 14:03 UTC, gaelkat commented
À

2023-11-10 09:09 UTC, StalkerVince approved these changes

2023-11-10 11:02 UTC, merged