S00 us10
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-Postify pull request #23
Opened 2023-11-09 10:40 UTC by StalkerVince

2023-11-09 10:48 UTC, Chikoulat approved these changes
Don't forget to lowerCase your CSS files.

2023-11-09 10:50 UTC, Lambseb approved these changes

2023-11-09 11:15 UTC, ioayoub requested changes
CamelCase is only allowed on Components and Classes
Please update your css and image files

2023-11-09 11:16 UTC, ioayoub requested changes

2023-11-09 11:16 UTC, ioayoub commented on frontend/src/components/Form.jsx
> +          <button type="button">Send Message</button>
French or English, but not both

2023-11-10 08:43 UTC, ioayoub approved these changes

2023-11-10 09:08 UTC, merged