Card Generator: Added Font-Family selector with +10 fonts
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-Postify pull request #27
Opened 2023-11-15 09:23 UTC by StalkerVince

2023-11-15 09:26 UTC, Chikoulat approved these changes

2023-11-15 09:31 UTC, Lambseb approved these changes
line 76  text not necessary  " >
          Bonjour, je suis un texte de test! XD"
  good job however

2023-11-16 17:00 UTC, ioayoub requested changes

2023-11-16 17:00 UTC, ioayoub commented on frontend/src/components/CardGeneration.jsx
> +      <select>
Well, fix this please :)

2023-11-16 17:11 UTC, ioayoub approved these changes
Top !

2023-11-16 17:11 UTC, ioayoub requested changes
Conflicts

2023-11-16 18:02 UTC, closed without merging