S04US13
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-Postify pull request #28
Opened 2023-11-15 11:30 UTC by Chikoulat

fix : fixed the display of selected picture in postcard page.
fix : fixed the search result to be dispayed in the results page.
feat : added the color background and police personalization for the postcard page. 
feat : added random pictures in the images page.

2023-11-15 11:34 UTC, Lambseb approved these changes
good job

2023-11-15 13:08 UTC, StalkerVince approved these changes

2023-11-15 17:14 UTC, ioayoub requested changes

2023-11-15 17:14 UTC, ioayoub commented on frontend/src/components/Presentation/Presentation.jsx
> +        <NavLink to="/Images" className="start">
links in lowercase please

2023-11-16 16:58 UTC, ioayoub approved these changes

2023-11-16 16:58 UTC, ioayoub requested changes
Conflicts

2023-11-16 17:25 UTC, ioayoub approved these changes

2023-11-17 10:10 UTC, merged