S04US10
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P2-Postify pull request #29
Opened 2023-11-15 16:37 UTC by Chikoulat

Update : added social media share button and email send button

2023-11-15 17:17 UTC, ioayoub requested changes

2023-11-15 17:17 UTC, ioayoub commented on frontend/src/components/ImageSample/ImageSample.jsx
> +  }, []); // Empty dependency array means this effect runs once, similar to componentDidMount
At least, remove these comments when you generate your code....

2023-11-15 17:17 UTC, ioayoub commented on frontend/src/main.jsx
> +        path: "Images",
lower case here

2023-11-16 13:36 UTC, StalkerVince approved these changes

2023-11-16 13:37 UTC, Lambseb approved these changes

2023-11-16 16:57 UTC, ioayoub approved these changes

2023-11-16 16:58 UTC, merged